resources:
- ./istio-bot
- ./istio-ingress
- ./gateway-env-config.yml
configurations:
- kustomize-reference.yaml
vars:
- name: ISTIO_VERSION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: gateway-env-config
  fieldref:
    fieldpath: data.ISTIO_VERSION
