apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  labels:
    scope: system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.16.1
    chart: istio/istiod
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector
      jsonPointers:
          - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-istio-system
      jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy
  project: istio
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
