resources:
- ../base/istio-istiod/istio-1.14.6
- ./kustomize-config.yaml
patchesStrategicMerge:
#- istio-istiod.yaml
configurations:
  - kustomize-reference.yaml
vars:
  - name: ISTIO_MESH_ID
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: istio-kustomize-config
    fieldref:
      fieldpath: data.MESH_ID
