apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  labels:
    scope: system
spec:
  source:
    targetRevision: 1.13.5
    helm:
      valueFiles:
        - values.yaml
